### ISSUE TITLE
加载报错

### ISSUE THREAD

**Issue by JevanWu** [icyleaf/wechat-bot#4]
```
/Users/jevan/.rvm/gems/ruby-2.4.1/gems/wechat-bot-0.1.0.alpha/lib/wechat/bot/ext/wechat_emoji_string.rb:1:in `<top (required)>': uninitialized constant WeChat (NameError)
	from /Users/jevan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/jevan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/jevan/.rvm/gems/ruby-2.4.1/gems/wechat-bot-0.1.0.alpha/lib/wechat/bot.rb:1:in `<top (required)>'
	from /Users/jevan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/jevan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/jevan/.rvm/gems/ruby-2.4.1/gems/wechat-bot-0.1.0.alpha/lib/wechat-bot.rb:1:in `<top (required)>'
	from /Users/jevan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Users/jevan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Users/jevan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
```

看文件结构 最顶部的module应该为Wechat?

**Comment by icyleaf** [comment]
看Rakefile，没有诚意的issue。
